@Orders_Abp_Host = http://localhost:5050
@orderId = 00000000-0000-0000-0000-000000000000

POST {{Orders_Abp_Host}}/api/app/order
Content-Type: application/json

{
  "customerName": "Alice Johnson",
  "totalAmount": 149.90
}

###
GET {{Orders_Abp_Host}}/api/app/order

###
GET {{Orders_Abp_Host}}/api/app/order/{{orderId}}

###
GET {{Orders_Abp_Host}}/health/ready
