@Orders.Api_HostAddress = http://localhost:8080

# Create a new order
POST {{Orders.Api_HostAddress}}/orders
Content-Type: application/json

{
  "customerName": "Ana Costa",
  "totalAmount": 120.50
}

### 

# Retrieve all orders
GET {{Orders.Api_HostAddress}}/orders
Accept: application/json


###

# Assuming we have an orderId from the previous POST response, we can retrieve that specific order
@orderId = {{orderId}}

GET {{Orders.Api_HostAddress}}/orders/{{orderId}}
Accept: application/json
